language: node_js
node_js:
- "node"

cache:
  directories:
  - "client/node_modules"

install:
- cd client
- npm install

script: npm test

before_deploy:
- cd ..
- npm install now --no-save

deploy:
- provider: script # Run a custom deployment script which we will define below
  script: now --token $NOW_TOKEN --public
  skip_cleanup: true
